/*
Shipping APIs

Testing MultipieceShipmentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sp360shipping

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/RKGuptaPB/sp360-shipping-go"
)

func Test_sp360shipping_MultipieceShipmentAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MultipieceShipmentAPIService MultipieceRates", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MultipieceShipmentAPI.MultipieceRates(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MultipieceShipmentAPIService MultipieceShipment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MultipieceShipmentAPI.MultipieceShipment(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MultipieceShipmentAPIService MultipieceShipmentCancel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var shipmentId string

		resp, httpRes, err := apiClient.MultipieceShipmentAPI.MultipieceShipmentCancel(context.Background(), shipmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MultipieceShipmentAPIService MultipieceShipmentReprint", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var shipmentId string

		resp, httpRes, err := apiClient.MultipieceShipmentAPI.MultipieceShipmentReprint(context.Background(), shipmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
