/*
Shipping APIs

The Shipping APIs include a variety of operations that allow users to manage and track their shipping requests.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sp360shipping

import (
	"encoding/json"
)

// checks if the SpecialServiceERRInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpecialServiceERRInner{}

// SpecialServiceERRInner struct for SpecialServiceERRInner
type SpecialServiceERRInner struct {
	// A unique identifier associate to the special service, which is to be applied.
	SpecialserviceId *string `json:"specialserviceId,omitempty"`
}

// NewSpecialServiceERRInner instantiates a new SpecialServiceERRInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpecialServiceERRInner() *SpecialServiceERRInner {
	this := SpecialServiceERRInner{}
	return &this
}

// NewSpecialServiceERRInnerWithDefaults instantiates a new SpecialServiceERRInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpecialServiceERRInnerWithDefaults() *SpecialServiceERRInner {
	this := SpecialServiceERRInner{}
	return &this
}

// GetSpecialserviceId returns the SpecialserviceId field value if set, zero value otherwise.
func (o *SpecialServiceERRInner) GetSpecialserviceId() string {
	if o == nil || IsNil(o.SpecialserviceId) {
		var ret string
		return ret
	}
	return *o.SpecialserviceId
}

// GetSpecialserviceIdOk returns a tuple with the SpecialserviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpecialServiceERRInner) GetSpecialserviceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SpecialserviceId) {
		return nil, false
	}
	return o.SpecialserviceId, true
}

// HasSpecialserviceId returns a boolean if a field has been set.
func (o *SpecialServiceERRInner) HasSpecialserviceId() bool {
	if o != nil && !IsNil(o.SpecialserviceId) {
		return true
	}

	return false
}

// SetSpecialserviceId gets a reference to the given string and assigns it to the SpecialserviceId field.
func (o *SpecialServiceERRInner) SetSpecialserviceId(v string) {
	o.SpecialserviceId = &v
}

func (o SpecialServiceERRInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpecialServiceERRInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SpecialserviceId) {
		toSerialize["specialserviceId"] = o.SpecialserviceId
	}
	return toSerialize, nil
}

type NullableSpecialServiceERRInner struct {
	value *SpecialServiceERRInner
	isSet bool
}

func (v NullableSpecialServiceERRInner) Get() *SpecialServiceERRInner {
	return v.value
}

func (v *NullableSpecialServiceERRInner) Set(val *SpecialServiceERRInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSpecialServiceERRInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSpecialServiceERRInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpecialServiceERRInner(val *SpecialServiceERRInner) *NullableSpecialServiceERRInner {
	return &NullableSpecialServiceERRInner{value: val, isSet: true}
}

func (v NullableSpecialServiceERRInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpecialServiceERRInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


