/*
Shipping APIs

The Shipping APIs include a variety of operations that allow users to manage and track their shipping requests.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sp360shipping

import (
	"encoding/json"
)

// checks if the SchedulePickupUSPSRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchedulePickupUSPSRequest{}

// SchedulePickupUSPSRequest struct for SchedulePickupUSPSRequest
type SchedulePickupUSPSRequest struct {
	// description
	PackageLocation *string `json:"packageLocation,omitempty"`
	// description
	CarrierAccountId *string `json:"carrierAccountId,omitempty"`
	PickupAddress *SchedulePickupDHLEXPRequestPickupAddress `json:"pickupAddress,omitempty"`
	// description
	PickupSummary []SchedulePickupUSPSRequestPickupSummaryInner `json:"pickupSummary,omitempty"`
	// description
	Additionalnotes *string `json:"additionalnotes,omitempty"`
	// description
	Reference *string `json:"reference,omitempty"`
}

// NewSchedulePickupUSPSRequest instantiates a new SchedulePickupUSPSRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchedulePickupUSPSRequest() *SchedulePickupUSPSRequest {
	this := SchedulePickupUSPSRequest{}
	return &this
}

// NewSchedulePickupUSPSRequestWithDefaults instantiates a new SchedulePickupUSPSRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchedulePickupUSPSRequestWithDefaults() *SchedulePickupUSPSRequest {
	this := SchedulePickupUSPSRequest{}
	return &this
}

// GetPackageLocation returns the PackageLocation field value if set, zero value otherwise.
func (o *SchedulePickupUSPSRequest) GetPackageLocation() string {
	if o == nil || IsNil(o.PackageLocation) {
		var ret string
		return ret
	}
	return *o.PackageLocation
}

// GetPackageLocationOk returns a tuple with the PackageLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchedulePickupUSPSRequest) GetPackageLocationOk() (*string, bool) {
	if o == nil || IsNil(o.PackageLocation) {
		return nil, false
	}
	return o.PackageLocation, true
}

// HasPackageLocation returns a boolean if a field has been set.
func (o *SchedulePickupUSPSRequest) HasPackageLocation() bool {
	if o != nil && !IsNil(o.PackageLocation) {
		return true
	}

	return false
}

// SetPackageLocation gets a reference to the given string and assigns it to the PackageLocation field.
func (o *SchedulePickupUSPSRequest) SetPackageLocation(v string) {
	o.PackageLocation = &v
}

// GetCarrierAccountId returns the CarrierAccountId field value if set, zero value otherwise.
func (o *SchedulePickupUSPSRequest) GetCarrierAccountId() string {
	if o == nil || IsNil(o.CarrierAccountId) {
		var ret string
		return ret
	}
	return *o.CarrierAccountId
}

// GetCarrierAccountIdOk returns a tuple with the CarrierAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchedulePickupUSPSRequest) GetCarrierAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierAccountId) {
		return nil, false
	}
	return o.CarrierAccountId, true
}

// HasCarrierAccountId returns a boolean if a field has been set.
func (o *SchedulePickupUSPSRequest) HasCarrierAccountId() bool {
	if o != nil && !IsNil(o.CarrierAccountId) {
		return true
	}

	return false
}

// SetCarrierAccountId gets a reference to the given string and assigns it to the CarrierAccountId field.
func (o *SchedulePickupUSPSRequest) SetCarrierAccountId(v string) {
	o.CarrierAccountId = &v
}

// GetPickupAddress returns the PickupAddress field value if set, zero value otherwise.
func (o *SchedulePickupUSPSRequest) GetPickupAddress() SchedulePickupDHLEXPRequestPickupAddress {
	if o == nil || IsNil(o.PickupAddress) {
		var ret SchedulePickupDHLEXPRequestPickupAddress
		return ret
	}
	return *o.PickupAddress
}

// GetPickupAddressOk returns a tuple with the PickupAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchedulePickupUSPSRequest) GetPickupAddressOk() (*SchedulePickupDHLEXPRequestPickupAddress, bool) {
	if o == nil || IsNil(o.PickupAddress) {
		return nil, false
	}
	return o.PickupAddress, true
}

// HasPickupAddress returns a boolean if a field has been set.
func (o *SchedulePickupUSPSRequest) HasPickupAddress() bool {
	if o != nil && !IsNil(o.PickupAddress) {
		return true
	}

	return false
}

// SetPickupAddress gets a reference to the given SchedulePickupDHLEXPRequestPickupAddress and assigns it to the PickupAddress field.
func (o *SchedulePickupUSPSRequest) SetPickupAddress(v SchedulePickupDHLEXPRequestPickupAddress) {
	o.PickupAddress = &v
}

// GetPickupSummary returns the PickupSummary field value if set, zero value otherwise.
func (o *SchedulePickupUSPSRequest) GetPickupSummary() []SchedulePickupUSPSRequestPickupSummaryInner {
	if o == nil || IsNil(o.PickupSummary) {
		var ret []SchedulePickupUSPSRequestPickupSummaryInner
		return ret
	}
	return o.PickupSummary
}

// GetPickupSummaryOk returns a tuple with the PickupSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchedulePickupUSPSRequest) GetPickupSummaryOk() ([]SchedulePickupUSPSRequestPickupSummaryInner, bool) {
	if o == nil || IsNil(o.PickupSummary) {
		return nil, false
	}
	return o.PickupSummary, true
}

// HasPickupSummary returns a boolean if a field has been set.
func (o *SchedulePickupUSPSRequest) HasPickupSummary() bool {
	if o != nil && !IsNil(o.PickupSummary) {
		return true
	}

	return false
}

// SetPickupSummary gets a reference to the given []SchedulePickupUSPSRequestPickupSummaryInner and assigns it to the PickupSummary field.
func (o *SchedulePickupUSPSRequest) SetPickupSummary(v []SchedulePickupUSPSRequestPickupSummaryInner) {
	o.PickupSummary = v
}

// GetAdditionalnotes returns the Additionalnotes field value if set, zero value otherwise.
func (o *SchedulePickupUSPSRequest) GetAdditionalnotes() string {
	if o == nil || IsNil(o.Additionalnotes) {
		var ret string
		return ret
	}
	return *o.Additionalnotes
}

// GetAdditionalnotesOk returns a tuple with the Additionalnotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchedulePickupUSPSRequest) GetAdditionalnotesOk() (*string, bool) {
	if o == nil || IsNil(o.Additionalnotes) {
		return nil, false
	}
	return o.Additionalnotes, true
}

// HasAdditionalnotes returns a boolean if a field has been set.
func (o *SchedulePickupUSPSRequest) HasAdditionalnotes() bool {
	if o != nil && !IsNil(o.Additionalnotes) {
		return true
	}

	return false
}

// SetAdditionalnotes gets a reference to the given string and assigns it to the Additionalnotes field.
func (o *SchedulePickupUSPSRequest) SetAdditionalnotes(v string) {
	o.Additionalnotes = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *SchedulePickupUSPSRequest) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchedulePickupUSPSRequest) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *SchedulePickupUSPSRequest) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *SchedulePickupUSPSRequest) SetReference(v string) {
	o.Reference = &v
}

func (o SchedulePickupUSPSRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchedulePickupUSPSRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PackageLocation) {
		toSerialize["packageLocation"] = o.PackageLocation
	}
	if !IsNil(o.CarrierAccountId) {
		toSerialize["carrierAccountId"] = o.CarrierAccountId
	}
	if !IsNil(o.PickupAddress) {
		toSerialize["pickupAddress"] = o.PickupAddress
	}
	if !IsNil(o.PickupSummary) {
		toSerialize["pickupSummary"] = o.PickupSummary
	}
	if !IsNil(o.Additionalnotes) {
		toSerialize["additionalnotes"] = o.Additionalnotes
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	return toSerialize, nil
}

type NullableSchedulePickupUSPSRequest struct {
	value *SchedulePickupUSPSRequest
	isSet bool
}

func (v NullableSchedulePickupUSPSRequest) Get() *SchedulePickupUSPSRequest {
	return v.value
}

func (v *NullableSchedulePickupUSPSRequest) Set(val *SchedulePickupUSPSRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSchedulePickupUSPSRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSchedulePickupUSPSRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchedulePickupUSPSRequest(val *SchedulePickupUSPSRequest) *NullableSchedulePickupUSPSRequest {
	return &NullableSchedulePickupUSPSRequest{value: val, isSet: true}
}

func (v NullableSchedulePickupUSPSRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchedulePickupUSPSRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


