/*
Shipping APIs

The Shipping APIs include a variety of operations that allow users to manage and track their shipping requests.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sp360shipping

import (
	"encoding/json"
)

// checks if the ReturnLabelResponseRateSpecialServicesInnerInputParametersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReturnLabelResponseRateSpecialServicesInnerInputParametersInner{}

// ReturnLabelResponseRateSpecialServicesInnerInputParametersInner struct for ReturnLabelResponseRateSpecialServicesInnerInputParametersInner
type ReturnLabelResponseRateSpecialServicesInnerInputParametersInner struct {
	// Description
	Name *string `json:"name,omitempty"`
	// Description
	Value *string `json:"value,omitempty"`
}

// NewReturnLabelResponseRateSpecialServicesInnerInputParametersInner instantiates a new ReturnLabelResponseRateSpecialServicesInnerInputParametersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReturnLabelResponseRateSpecialServicesInnerInputParametersInner() *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner {
	this := ReturnLabelResponseRateSpecialServicesInnerInputParametersInner{}
	return &this
}

// NewReturnLabelResponseRateSpecialServicesInnerInputParametersInnerWithDefaults instantiates a new ReturnLabelResponseRateSpecialServicesInnerInputParametersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReturnLabelResponseRateSpecialServicesInnerInputParametersInnerWithDefaults() *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner {
	this := ReturnLabelResponseRateSpecialServicesInnerInputParametersInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner) SetValue(v string) {
	o.Value = &v
}

func (o ReturnLabelResponseRateSpecialServicesInnerInputParametersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReturnLabelResponseRateSpecialServicesInnerInputParametersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableReturnLabelResponseRateSpecialServicesInnerInputParametersInner struct {
	value *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner
	isSet bool
}

func (v NullableReturnLabelResponseRateSpecialServicesInnerInputParametersInner) Get() *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner {
	return v.value
}

func (v *NullableReturnLabelResponseRateSpecialServicesInnerInputParametersInner) Set(val *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableReturnLabelResponseRateSpecialServicesInnerInputParametersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableReturnLabelResponseRateSpecialServicesInnerInputParametersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReturnLabelResponseRateSpecialServicesInnerInputParametersInner(val *ReturnLabelResponseRateSpecialServicesInnerInputParametersInner) *NullableReturnLabelResponseRateSpecialServicesInnerInputParametersInner {
	return &NullableReturnLabelResponseRateSpecialServicesInnerInputParametersInner{value: val, isSet: true}
}

func (v NullableReturnLabelResponseRateSpecialServicesInnerInputParametersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReturnLabelResponseRateSpecialServicesInnerInputParametersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


