/*
Shipping APIs

The Shipping APIs include a variety of operations that allow users to manage and track their shipping requests.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sp360shipping

import (
	"encoding/json"
)

// checks if the GetSingleShipment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSingleShipment{}

// GetSingleShipment struct for GetSingleShipment
type GetSingleShipment struct {
	// Key assigned by the shipping system to the transaction.
	CorrelationId *string `json:"correlationId,omitempty"`
	FromAddress *GetSingleShipmentFromAddress `json:"fromAddress,omitempty"`
	Parcel *ReturnLabelParcel `json:"parcel,omitempty"`
	// Additional metadata that needs to be stored for this shipment can be added here. For now, 'Cost Account Name' is supported.
	Metadata []GetAllShipmentsDataInnerMetadataInner `json:"metadata,omitempty"`
	// A unique identifier associated with the Parcel.
	ParcelId *string `json:"parcelId,omitempty"`
	// The Tracking number given to the Parcel for tracking purpose.
	ParcelTrackingNumber *string `json:"parcelTrackingNumber,omitempty"`
	Rate *GetSingleShipmentRate `json:"rate,omitempty"`
	// The carrier-based service that is used for shipment.
	Service *string `json:"service,omitempty"`
	// A unique identifier associated with Shipment ID, which is used for Reprint and Cancel.
	ShipmentId *string `json:"shipmentId,omitempty"`
	// The status of the Shipment.
	Status *string `json:"status,omitempty"`
	ToAddress *GetSingleShipmentToAddress `json:"toAddress,omitempty"`
}

// NewGetSingleShipment instantiates a new GetSingleShipment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSingleShipment() *GetSingleShipment {
	this := GetSingleShipment{}
	return &this
}

// NewGetSingleShipmentWithDefaults instantiates a new GetSingleShipment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSingleShipmentWithDefaults() *GetSingleShipment {
	this := GetSingleShipment{}
	return &this
}

// GetCorrelationId returns the CorrelationId field value if set, zero value otherwise.
func (o *GetSingleShipment) GetCorrelationId() string {
	if o == nil || IsNil(o.CorrelationId) {
		var ret string
		return ret
	}
	return *o.CorrelationId
}

// GetCorrelationIdOk returns a tuple with the CorrelationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleShipment) GetCorrelationIdOk() (*string, bool) {
	if o == nil || IsNil(o.CorrelationId) {
		return nil, false
	}
	return o.CorrelationId, true
}

// HasCorrelationId returns a boolean if a field has been set.
func (o *GetSingleShipment) HasCorrelationId() bool {
	if o != nil && !IsNil(o.CorrelationId) {
		return true
	}

	return false
}

// SetCorrelationId gets a reference to the given string and assigns it to the CorrelationId field.
func (o *GetSingleShipment) SetCorrelationId(v string) {
	o.CorrelationId = &v
}

// GetFromAddress returns the FromAddress field value if set, zero value otherwise.
func (o *GetSingleShipment) GetFromAddress() GetSingleShipmentFromAddress {
	if o == nil || IsNil(o.FromAddress) {
		var ret GetSingleShipmentFromAddress
		return ret
	}
	return *o.FromAddress
}

// GetFromAddressOk returns a tuple with the FromAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleShipment) GetFromAddressOk() (*GetSingleShipmentFromAddress, bool) {
	if o == nil || IsNil(o.FromAddress) {
		return nil, false
	}
	return o.FromAddress, true
}

// HasFromAddress returns a boolean if a field has been set.
func (o *GetSingleShipment) HasFromAddress() bool {
	if o != nil && !IsNil(o.FromAddress) {
		return true
	}

	return false
}

// SetFromAddress gets a reference to the given GetSingleShipmentFromAddress and assigns it to the FromAddress field.
func (o *GetSingleShipment) SetFromAddress(v GetSingleShipmentFromAddress) {
	o.FromAddress = &v
}

// GetParcel returns the Parcel field value if set, zero value otherwise.
func (o *GetSingleShipment) GetParcel() ReturnLabelParcel {
	if o == nil || IsNil(o.Parcel) {
		var ret ReturnLabelParcel
		return ret
	}
	return *o.Parcel
}

// GetParcelOk returns a tuple with the Parcel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleShipment) GetParcelOk() (*ReturnLabelParcel, bool) {
	if o == nil || IsNil(o.Parcel) {
		return nil, false
	}
	return o.Parcel, true
}

// HasParcel returns a boolean if a field has been set.
func (o *GetSingleShipment) HasParcel() bool {
	if o != nil && !IsNil(o.Parcel) {
		return true
	}

	return false
}

// SetParcel gets a reference to the given ReturnLabelParcel and assigns it to the Parcel field.
func (o *GetSingleShipment) SetParcel(v ReturnLabelParcel) {
	o.Parcel = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *GetSingleShipment) GetMetadata() []GetAllShipmentsDataInnerMetadataInner {
	if o == nil || IsNil(o.Metadata) {
		var ret []GetAllShipmentsDataInnerMetadataInner
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleShipment) GetMetadataOk() ([]GetAllShipmentsDataInnerMetadataInner, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *GetSingleShipment) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []GetAllShipmentsDataInnerMetadataInner and assigns it to the Metadata field.
func (o *GetSingleShipment) SetMetadata(v []GetAllShipmentsDataInnerMetadataInner) {
	o.Metadata = v
}

// GetParcelId returns the ParcelId field value if set, zero value otherwise.
func (o *GetSingleShipment) GetParcelId() string {
	if o == nil || IsNil(o.ParcelId) {
		var ret string
		return ret
	}
	return *o.ParcelId
}

// GetParcelIdOk returns a tuple with the ParcelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleShipment) GetParcelIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParcelId) {
		return nil, false
	}
	return o.ParcelId, true
}

// HasParcelId returns a boolean if a field has been set.
func (o *GetSingleShipment) HasParcelId() bool {
	if o != nil && !IsNil(o.ParcelId) {
		return true
	}

	return false
}

// SetParcelId gets a reference to the given string and assigns it to the ParcelId field.
func (o *GetSingleShipment) SetParcelId(v string) {
	o.ParcelId = &v
}

// GetParcelTrackingNumber returns the ParcelTrackingNumber field value if set, zero value otherwise.
func (o *GetSingleShipment) GetParcelTrackingNumber() string {
	if o == nil || IsNil(o.ParcelTrackingNumber) {
		var ret string
		return ret
	}
	return *o.ParcelTrackingNumber
}

// GetParcelTrackingNumberOk returns a tuple with the ParcelTrackingNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleShipment) GetParcelTrackingNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ParcelTrackingNumber) {
		return nil, false
	}
	return o.ParcelTrackingNumber, true
}

// HasParcelTrackingNumber returns a boolean if a field has been set.
func (o *GetSingleShipment) HasParcelTrackingNumber() bool {
	if o != nil && !IsNil(o.ParcelTrackingNumber) {
		return true
	}

	return false
}

// SetParcelTrackingNumber gets a reference to the given string and assigns it to the ParcelTrackingNumber field.
func (o *GetSingleShipment) SetParcelTrackingNumber(v string) {
	o.ParcelTrackingNumber = &v
}

// GetRate returns the Rate field value if set, zero value otherwise.
func (o *GetSingleShipment) GetRate() GetSingleShipmentRate {
	if o == nil || IsNil(o.Rate) {
		var ret GetSingleShipmentRate
		return ret
	}
	return *o.Rate
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleShipment) GetRateOk() (*GetSingleShipmentRate, bool) {
	if o == nil || IsNil(o.Rate) {
		return nil, false
	}
	return o.Rate, true
}

// HasRate returns a boolean if a field has been set.
func (o *GetSingleShipment) HasRate() bool {
	if o != nil && !IsNil(o.Rate) {
		return true
	}

	return false
}

// SetRate gets a reference to the given GetSingleShipmentRate and assigns it to the Rate field.
func (o *GetSingleShipment) SetRate(v GetSingleShipmentRate) {
	o.Rate = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *GetSingleShipment) GetService() string {
	if o == nil || IsNil(o.Service) {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleShipment) GetServiceOk() (*string, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *GetSingleShipment) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *GetSingleShipment) SetService(v string) {
	o.Service = &v
}

// GetShipmentId returns the ShipmentId field value if set, zero value otherwise.
func (o *GetSingleShipment) GetShipmentId() string {
	if o == nil || IsNil(o.ShipmentId) {
		var ret string
		return ret
	}
	return *o.ShipmentId
}

// GetShipmentIdOk returns a tuple with the ShipmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleShipment) GetShipmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ShipmentId) {
		return nil, false
	}
	return o.ShipmentId, true
}

// HasShipmentId returns a boolean if a field has been set.
func (o *GetSingleShipment) HasShipmentId() bool {
	if o != nil && !IsNil(o.ShipmentId) {
		return true
	}

	return false
}

// SetShipmentId gets a reference to the given string and assigns it to the ShipmentId field.
func (o *GetSingleShipment) SetShipmentId(v string) {
	o.ShipmentId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetSingleShipment) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleShipment) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetSingleShipment) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetSingleShipment) SetStatus(v string) {
	o.Status = &v
}

// GetToAddress returns the ToAddress field value if set, zero value otherwise.
func (o *GetSingleShipment) GetToAddress() GetSingleShipmentToAddress {
	if o == nil || IsNil(o.ToAddress) {
		var ret GetSingleShipmentToAddress
		return ret
	}
	return *o.ToAddress
}

// GetToAddressOk returns a tuple with the ToAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleShipment) GetToAddressOk() (*GetSingleShipmentToAddress, bool) {
	if o == nil || IsNil(o.ToAddress) {
		return nil, false
	}
	return o.ToAddress, true
}

// HasToAddress returns a boolean if a field has been set.
func (o *GetSingleShipment) HasToAddress() bool {
	if o != nil && !IsNil(o.ToAddress) {
		return true
	}

	return false
}

// SetToAddress gets a reference to the given GetSingleShipmentToAddress and assigns it to the ToAddress field.
func (o *GetSingleShipment) SetToAddress(v GetSingleShipmentToAddress) {
	o.ToAddress = &v
}

func (o GetSingleShipment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSingleShipment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CorrelationId) {
		toSerialize["correlationId"] = o.CorrelationId
	}
	if !IsNil(o.FromAddress) {
		toSerialize["fromAddress"] = o.FromAddress
	}
	if !IsNil(o.Parcel) {
		toSerialize["parcel"] = o.Parcel
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.ParcelId) {
		toSerialize["parcelId"] = o.ParcelId
	}
	if !IsNil(o.ParcelTrackingNumber) {
		toSerialize["parcelTrackingNumber"] = o.ParcelTrackingNumber
	}
	if !IsNil(o.Rate) {
		toSerialize["rate"] = o.Rate
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.ShipmentId) {
		toSerialize["shipmentId"] = o.ShipmentId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ToAddress) {
		toSerialize["toAddress"] = o.ToAddress
	}
	return toSerialize, nil
}

type NullableGetSingleShipment struct {
	value *GetSingleShipment
	isSet bool
}

func (v NullableGetSingleShipment) Get() *GetSingleShipment {
	return v.value
}

func (v *NullableGetSingleShipment) Set(val *GetSingleShipment) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSingleShipment) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSingleShipment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSingleShipment(val *GetSingleShipment) *NullableGetSingleShipment {
	return &NullableGetSingleShipment{value: val, isSet: true}
}

func (v NullableGetSingleShipment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSingleShipment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


