/*
Shipping APIs

The Shipping APIs include a variety of operations that allow users to manage and track their shipping requests.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sp360shipping

import (
	"encoding/json"
)

// checks if the CarriersCarriersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CarriersCarriersInner{}

// CarriersCarriersInner struct for CarriersCarriersInner
type CarriersCarriersInner struct {
	// A unique identifier associated with the specific carrier.
	CarrierID *string `json:"carrierID,omitempty"`
	// This is the name of the Carrier, a shipping service which is used to carry shipment (e.g., parcels/packages/envelopes) from one place to other.
	Name *string `json:"name,omitempty"`
	// The two-character ISO Code of the source country from this ISO country list.
	OriginCountry *string `json:"originCountry,omitempty"`
	Properties *CarriersCarriersInnerProperties `json:"properties,omitempty"`
}

// NewCarriersCarriersInner instantiates a new CarriersCarriersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCarriersCarriersInner() *CarriersCarriersInner {
	this := CarriersCarriersInner{}
	return &this
}

// NewCarriersCarriersInnerWithDefaults instantiates a new CarriersCarriersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCarriersCarriersInnerWithDefaults() *CarriersCarriersInner {
	this := CarriersCarriersInner{}
	return &this
}

// GetCarrierID returns the CarrierID field value if set, zero value otherwise.
func (o *CarriersCarriersInner) GetCarrierID() string {
	if o == nil || IsNil(o.CarrierID) {
		var ret string
		return ret
	}
	return *o.CarrierID
}

// GetCarrierIDOk returns a tuple with the CarrierID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CarriersCarriersInner) GetCarrierIDOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierID) {
		return nil, false
	}
	return o.CarrierID, true
}

// HasCarrierID returns a boolean if a field has been set.
func (o *CarriersCarriersInner) HasCarrierID() bool {
	if o != nil && !IsNil(o.CarrierID) {
		return true
	}

	return false
}

// SetCarrierID gets a reference to the given string and assigns it to the CarrierID field.
func (o *CarriersCarriersInner) SetCarrierID(v string) {
	o.CarrierID = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CarriersCarriersInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CarriersCarriersInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CarriersCarriersInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CarriersCarriersInner) SetName(v string) {
	o.Name = &v
}

// GetOriginCountry returns the OriginCountry field value if set, zero value otherwise.
func (o *CarriersCarriersInner) GetOriginCountry() string {
	if o == nil || IsNil(o.OriginCountry) {
		var ret string
		return ret
	}
	return *o.OriginCountry
}

// GetOriginCountryOk returns a tuple with the OriginCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CarriersCarriersInner) GetOriginCountryOk() (*string, bool) {
	if o == nil || IsNil(o.OriginCountry) {
		return nil, false
	}
	return o.OriginCountry, true
}

// HasOriginCountry returns a boolean if a field has been set.
func (o *CarriersCarriersInner) HasOriginCountry() bool {
	if o != nil && !IsNil(o.OriginCountry) {
		return true
	}

	return false
}

// SetOriginCountry gets a reference to the given string and assigns it to the OriginCountry field.
func (o *CarriersCarriersInner) SetOriginCountry(v string) {
	o.OriginCountry = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *CarriersCarriersInner) GetProperties() CarriersCarriersInnerProperties {
	if o == nil || IsNil(o.Properties) {
		var ret CarriersCarriersInnerProperties
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CarriersCarriersInner) GetPropertiesOk() (*CarriersCarriersInnerProperties, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *CarriersCarriersInner) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given CarriersCarriersInnerProperties and assigns it to the Properties field.
func (o *CarriersCarriersInner) SetProperties(v CarriersCarriersInnerProperties) {
	o.Properties = &v
}

func (o CarriersCarriersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CarriersCarriersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CarrierID) {
		toSerialize["carrierID"] = o.CarrierID
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OriginCountry) {
		toSerialize["originCountry"] = o.OriginCountry
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	return toSerialize, nil
}

type NullableCarriersCarriersInner struct {
	value *CarriersCarriersInner
	isSet bool
}

func (v NullableCarriersCarriersInner) Get() *CarriersCarriersInner {
	return v.value
}

func (v *NullableCarriersCarriersInner) Set(val *CarriersCarriersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCarriersCarriersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCarriersCarriersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCarriersCarriersInner(val *CarriersCarriersInner) *NullableCarriersCarriersInner {
	return &NullableCarriersCarriersInner{value: val, isSet: true}
}

func (v NullableCarriersCarriersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCarriersCarriersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


