/*
Shipping APIs

The Shipping APIs include a variety of operations that allow users to manage and track their shipping requests.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sp360shipping

import (
	"encoding/json"
)

// checks if the RateShopResponseRatesInnerSurchargesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RateShopResponseRatesInnerSurchargesInner{}

// RateShopResponseRatesInnerSurchargesInner struct for RateShopResponseRatesInnerSurchargesInner
type RateShopResponseRatesInnerSurchargesInner struct {
	// The amount of the surcharge.
	Fee *float32 `json:"fee,omitempty"`
	// The type of surcharge.
	Name *string `json:"name,omitempty"`
}

// NewRateShopResponseRatesInnerSurchargesInner instantiates a new RateShopResponseRatesInnerSurchargesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRateShopResponseRatesInnerSurchargesInner() *RateShopResponseRatesInnerSurchargesInner {
	this := RateShopResponseRatesInnerSurchargesInner{}
	return &this
}

// NewRateShopResponseRatesInnerSurchargesInnerWithDefaults instantiates a new RateShopResponseRatesInnerSurchargesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRateShopResponseRatesInnerSurchargesInnerWithDefaults() *RateShopResponseRatesInnerSurchargesInner {
	this := RateShopResponseRatesInnerSurchargesInner{}
	return &this
}

// GetFee returns the Fee field value if set, zero value otherwise.
func (o *RateShopResponseRatesInnerSurchargesInner) GetFee() float32 {
	if o == nil || IsNil(o.Fee) {
		var ret float32
		return ret
	}
	return *o.Fee
}

// GetFeeOk returns a tuple with the Fee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RateShopResponseRatesInnerSurchargesInner) GetFeeOk() (*float32, bool) {
	if o == nil || IsNil(o.Fee) {
		return nil, false
	}
	return o.Fee, true
}

// HasFee returns a boolean if a field has been set.
func (o *RateShopResponseRatesInnerSurchargesInner) HasFee() bool {
	if o != nil && !IsNil(o.Fee) {
		return true
	}

	return false
}

// SetFee gets a reference to the given float32 and assigns it to the Fee field.
func (o *RateShopResponseRatesInnerSurchargesInner) SetFee(v float32) {
	o.Fee = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RateShopResponseRatesInnerSurchargesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RateShopResponseRatesInnerSurchargesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RateShopResponseRatesInnerSurchargesInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RateShopResponseRatesInnerSurchargesInner) SetName(v string) {
	o.Name = &v
}

func (o RateShopResponseRatesInnerSurchargesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RateShopResponseRatesInnerSurchargesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Fee) {
		toSerialize["fee"] = o.Fee
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableRateShopResponseRatesInnerSurchargesInner struct {
	value *RateShopResponseRatesInnerSurchargesInner
	isSet bool
}

func (v NullableRateShopResponseRatesInnerSurchargesInner) Get() *RateShopResponseRatesInnerSurchargesInner {
	return v.value
}

func (v *NullableRateShopResponseRatesInnerSurchargesInner) Set(val *RateShopResponseRatesInnerSurchargesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRateShopResponseRatesInnerSurchargesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRateShopResponseRatesInnerSurchargesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRateShopResponseRatesInnerSurchargesInner(val *RateShopResponseRatesInnerSurchargesInner) *NullableRateShopResponseRatesInnerSurchargesInner {
	return &NullableRateShopResponseRatesInnerSurchargesInner{value: val, isSet: true}
}

func (v NullableRateShopResponseRatesInnerSurchargesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRateShopResponseRatesInnerSurchargesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


