/*
Shipping APIs

The Shipping APIs include a variety of operations that allow users to manage and track their shipping requests.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sp360shipping

import (
	"encoding/json"
)

// checks if the SingleRateResponseRatesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SingleRateResponseRatesInner{}

// SingleRateResponseRatesInner struct for SingleRateResponseRatesInner
type SingleRateResponseRatesInner struct {
	// The base service charge is payable to the carrier, excluding special service charges.
	BaseCharge *float32 `json:"baseCharge,omitempty"`
	// Carrier is a service used to transport the parcels or couriers from one place to another.
	Carrier *string `json:"carrier,omitempty"`
	// Carrier Account is the account associated to specific carrier service.
	CarrierAccount *string `json:"carrierAccount,omitempty"`
	DeliveryCommitment *RateShopResponseRatesInnerDeliveryCommitment `json:"deliveryCommitment,omitempty"`
	// Parcel Type is required for creating a shipment while rating a parcel, which varies as per Carrier selection. ParcelType have categories like Package, Envelopes, Paks, Boxes, Tube, etc. 
	ParcelType *string `json:"parcelType,omitempty"`
	// Its value can be CONTRACT_RATES, COMMERCIAL or COMMERCIAL_BASE for USPS and COMMERCIAL for other carriers depending on the Pitney Bowes contract/subscription
	RateTypeId *string `json:"rateTypeId,omitempty"`
	// The unique identifier given to the carrier specific service.
	ServiceId *string `json:"serviceId,omitempty"`
	//  It provides a carrier-service based special or extra service.
	SpecialServices []SingleRateResponseRatesInnerSpecialServicesInner `json:"specialServices,omitempty"`
	// The total amount payable to the carrier, including special service fees, surcharges, and any international taxes and duties.
	TotalCarrierCharge *float32 `json:"totalCarrierCharge,omitempty"`
}

// NewSingleRateResponseRatesInner instantiates a new SingleRateResponseRatesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSingleRateResponseRatesInner() *SingleRateResponseRatesInner {
	this := SingleRateResponseRatesInner{}
	return &this
}

// NewSingleRateResponseRatesInnerWithDefaults instantiates a new SingleRateResponseRatesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSingleRateResponseRatesInnerWithDefaults() *SingleRateResponseRatesInner {
	this := SingleRateResponseRatesInner{}
	return &this
}

// GetBaseCharge returns the BaseCharge field value if set, zero value otherwise.
func (o *SingleRateResponseRatesInner) GetBaseCharge() float32 {
	if o == nil || IsNil(o.BaseCharge) {
		var ret float32
		return ret
	}
	return *o.BaseCharge
}

// GetBaseChargeOk returns a tuple with the BaseCharge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SingleRateResponseRatesInner) GetBaseChargeOk() (*float32, bool) {
	if o == nil || IsNil(o.BaseCharge) {
		return nil, false
	}
	return o.BaseCharge, true
}

// HasBaseCharge returns a boolean if a field has been set.
func (o *SingleRateResponseRatesInner) HasBaseCharge() bool {
	if o != nil && !IsNil(o.BaseCharge) {
		return true
	}

	return false
}

// SetBaseCharge gets a reference to the given float32 and assigns it to the BaseCharge field.
func (o *SingleRateResponseRatesInner) SetBaseCharge(v float32) {
	o.BaseCharge = &v
}

// GetCarrier returns the Carrier field value if set, zero value otherwise.
func (o *SingleRateResponseRatesInner) GetCarrier() string {
	if o == nil || IsNil(o.Carrier) {
		var ret string
		return ret
	}
	return *o.Carrier
}

// GetCarrierOk returns a tuple with the Carrier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SingleRateResponseRatesInner) GetCarrierOk() (*string, bool) {
	if o == nil || IsNil(o.Carrier) {
		return nil, false
	}
	return o.Carrier, true
}

// HasCarrier returns a boolean if a field has been set.
func (o *SingleRateResponseRatesInner) HasCarrier() bool {
	if o != nil && !IsNil(o.Carrier) {
		return true
	}

	return false
}

// SetCarrier gets a reference to the given string and assigns it to the Carrier field.
func (o *SingleRateResponseRatesInner) SetCarrier(v string) {
	o.Carrier = &v
}

// GetCarrierAccount returns the CarrierAccount field value if set, zero value otherwise.
func (o *SingleRateResponseRatesInner) GetCarrierAccount() string {
	if o == nil || IsNil(o.CarrierAccount) {
		var ret string
		return ret
	}
	return *o.CarrierAccount
}

// GetCarrierAccountOk returns a tuple with the CarrierAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SingleRateResponseRatesInner) GetCarrierAccountOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierAccount) {
		return nil, false
	}
	return o.CarrierAccount, true
}

// HasCarrierAccount returns a boolean if a field has been set.
func (o *SingleRateResponseRatesInner) HasCarrierAccount() bool {
	if o != nil && !IsNil(o.CarrierAccount) {
		return true
	}

	return false
}

// SetCarrierAccount gets a reference to the given string and assigns it to the CarrierAccount field.
func (o *SingleRateResponseRatesInner) SetCarrierAccount(v string) {
	o.CarrierAccount = &v
}

// GetDeliveryCommitment returns the DeliveryCommitment field value if set, zero value otherwise.
func (o *SingleRateResponseRatesInner) GetDeliveryCommitment() RateShopResponseRatesInnerDeliveryCommitment {
	if o == nil || IsNil(o.DeliveryCommitment) {
		var ret RateShopResponseRatesInnerDeliveryCommitment
		return ret
	}
	return *o.DeliveryCommitment
}

// GetDeliveryCommitmentOk returns a tuple with the DeliveryCommitment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SingleRateResponseRatesInner) GetDeliveryCommitmentOk() (*RateShopResponseRatesInnerDeliveryCommitment, bool) {
	if o == nil || IsNil(o.DeliveryCommitment) {
		return nil, false
	}
	return o.DeliveryCommitment, true
}

// HasDeliveryCommitment returns a boolean if a field has been set.
func (o *SingleRateResponseRatesInner) HasDeliveryCommitment() bool {
	if o != nil && !IsNil(o.DeliveryCommitment) {
		return true
	}

	return false
}

// SetDeliveryCommitment gets a reference to the given RateShopResponseRatesInnerDeliveryCommitment and assigns it to the DeliveryCommitment field.
func (o *SingleRateResponseRatesInner) SetDeliveryCommitment(v RateShopResponseRatesInnerDeliveryCommitment) {
	o.DeliveryCommitment = &v
}

// GetParcelType returns the ParcelType field value if set, zero value otherwise.
func (o *SingleRateResponseRatesInner) GetParcelType() string {
	if o == nil || IsNil(o.ParcelType) {
		var ret string
		return ret
	}
	return *o.ParcelType
}

// GetParcelTypeOk returns a tuple with the ParcelType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SingleRateResponseRatesInner) GetParcelTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ParcelType) {
		return nil, false
	}
	return o.ParcelType, true
}

// HasParcelType returns a boolean if a field has been set.
func (o *SingleRateResponseRatesInner) HasParcelType() bool {
	if o != nil && !IsNil(o.ParcelType) {
		return true
	}

	return false
}

// SetParcelType gets a reference to the given string and assigns it to the ParcelType field.
func (o *SingleRateResponseRatesInner) SetParcelType(v string) {
	o.ParcelType = &v
}

// GetRateTypeId returns the RateTypeId field value if set, zero value otherwise.
func (o *SingleRateResponseRatesInner) GetRateTypeId() string {
	if o == nil || IsNil(o.RateTypeId) {
		var ret string
		return ret
	}
	return *o.RateTypeId
}

// GetRateTypeIdOk returns a tuple with the RateTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SingleRateResponseRatesInner) GetRateTypeIdOk() (*string, bool) {
	if o == nil || IsNil(o.RateTypeId) {
		return nil, false
	}
	return o.RateTypeId, true
}

// HasRateTypeId returns a boolean if a field has been set.
func (o *SingleRateResponseRatesInner) HasRateTypeId() bool {
	if o != nil && !IsNil(o.RateTypeId) {
		return true
	}

	return false
}

// SetRateTypeId gets a reference to the given string and assigns it to the RateTypeId field.
func (o *SingleRateResponseRatesInner) SetRateTypeId(v string) {
	o.RateTypeId = &v
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise.
func (o *SingleRateResponseRatesInner) GetServiceId() string {
	if o == nil || IsNil(o.ServiceId) {
		var ret string
		return ret
	}
	return *o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SingleRateResponseRatesInner) GetServiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceId) {
		return nil, false
	}
	return o.ServiceId, true
}

// HasServiceId returns a boolean if a field has been set.
func (o *SingleRateResponseRatesInner) HasServiceId() bool {
	if o != nil && !IsNil(o.ServiceId) {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given string and assigns it to the ServiceId field.
func (o *SingleRateResponseRatesInner) SetServiceId(v string) {
	o.ServiceId = &v
}

// GetSpecialServices returns the SpecialServices field value if set, zero value otherwise.
func (o *SingleRateResponseRatesInner) GetSpecialServices() []SingleRateResponseRatesInnerSpecialServicesInner {
	if o == nil || IsNil(o.SpecialServices) {
		var ret []SingleRateResponseRatesInnerSpecialServicesInner
		return ret
	}
	return o.SpecialServices
}

// GetSpecialServicesOk returns a tuple with the SpecialServices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SingleRateResponseRatesInner) GetSpecialServicesOk() ([]SingleRateResponseRatesInnerSpecialServicesInner, bool) {
	if o == nil || IsNil(o.SpecialServices) {
		return nil, false
	}
	return o.SpecialServices, true
}

// HasSpecialServices returns a boolean if a field has been set.
func (o *SingleRateResponseRatesInner) HasSpecialServices() bool {
	if o != nil && !IsNil(o.SpecialServices) {
		return true
	}

	return false
}

// SetSpecialServices gets a reference to the given []SingleRateResponseRatesInnerSpecialServicesInner and assigns it to the SpecialServices field.
func (o *SingleRateResponseRatesInner) SetSpecialServices(v []SingleRateResponseRatesInnerSpecialServicesInner) {
	o.SpecialServices = v
}

// GetTotalCarrierCharge returns the TotalCarrierCharge field value if set, zero value otherwise.
func (o *SingleRateResponseRatesInner) GetTotalCarrierCharge() float32 {
	if o == nil || IsNil(o.TotalCarrierCharge) {
		var ret float32
		return ret
	}
	return *o.TotalCarrierCharge
}

// GetTotalCarrierChargeOk returns a tuple with the TotalCarrierCharge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SingleRateResponseRatesInner) GetTotalCarrierChargeOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalCarrierCharge) {
		return nil, false
	}
	return o.TotalCarrierCharge, true
}

// HasTotalCarrierCharge returns a boolean if a field has been set.
func (o *SingleRateResponseRatesInner) HasTotalCarrierCharge() bool {
	if o != nil && !IsNil(o.TotalCarrierCharge) {
		return true
	}

	return false
}

// SetTotalCarrierCharge gets a reference to the given float32 and assigns it to the TotalCarrierCharge field.
func (o *SingleRateResponseRatesInner) SetTotalCarrierCharge(v float32) {
	o.TotalCarrierCharge = &v
}

func (o SingleRateResponseRatesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SingleRateResponseRatesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BaseCharge) {
		toSerialize["baseCharge"] = o.BaseCharge
	}
	if !IsNil(o.Carrier) {
		toSerialize["carrier"] = o.Carrier
	}
	if !IsNil(o.CarrierAccount) {
		toSerialize["carrierAccount"] = o.CarrierAccount
	}
	if !IsNil(o.DeliveryCommitment) {
		toSerialize["deliveryCommitment"] = o.DeliveryCommitment
	}
	if !IsNil(o.ParcelType) {
		toSerialize["parcelType"] = o.ParcelType
	}
	if !IsNil(o.RateTypeId) {
		toSerialize["rateTypeId"] = o.RateTypeId
	}
	if !IsNil(o.ServiceId) {
		toSerialize["serviceId"] = o.ServiceId
	}
	if !IsNil(o.SpecialServices) {
		toSerialize["specialServices"] = o.SpecialServices
	}
	if !IsNil(o.TotalCarrierCharge) {
		toSerialize["totalCarrierCharge"] = o.TotalCarrierCharge
	}
	return toSerialize, nil
}

type NullableSingleRateResponseRatesInner struct {
	value *SingleRateResponseRatesInner
	isSet bool
}

func (v NullableSingleRateResponseRatesInner) Get() *SingleRateResponseRatesInner {
	return v.value
}

func (v *NullableSingleRateResponseRatesInner) Set(val *SingleRateResponseRatesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSingleRateResponseRatesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSingleRateResponseRatesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSingleRateResponseRatesInner(val *SingleRateResponseRatesInner) *NullableSingleRateResponseRatesInner {
	return &NullableSingleRateResponseRatesInner{value: val, isSet: true}
}

func (v NullableSingleRateResponseRatesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSingleRateResponseRatesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


