/*
Shipping APIs

The Shipping APIs include a variety of operations that allow users to manage and track their shipping requests.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sp360shipping

import (
	"encoding/json"
)

// checks if the PrintDocumentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrintDocumentResponse{}

// PrintDocumentResponse struct for PrintDocumentResponse
type PrintDocumentResponse struct {
	// Job Id can be used to check the status of the request.
	JobId *string `json:"jobId,omitempty"`
}

// NewPrintDocumentResponse instantiates a new PrintDocumentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrintDocumentResponse() *PrintDocumentResponse {
	this := PrintDocumentResponse{}
	return &this
}

// NewPrintDocumentResponseWithDefaults instantiates a new PrintDocumentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrintDocumentResponseWithDefaults() *PrintDocumentResponse {
	this := PrintDocumentResponse{}
	return &this
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *PrintDocumentResponse) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrintDocumentResponse) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *PrintDocumentResponse) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *PrintDocumentResponse) SetJobId(v string) {
	o.JobId = &v
}

func (o PrintDocumentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrintDocumentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JobId) {
		toSerialize["jobId"] = o.JobId
	}
	return toSerialize, nil
}

type NullablePrintDocumentResponse struct {
	value *PrintDocumentResponse
	isSet bool
}

func (v NullablePrintDocumentResponse) Get() *PrintDocumentResponse {
	return v.value
}

func (v *NullablePrintDocumentResponse) Set(val *PrintDocumentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePrintDocumentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePrintDocumentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrintDocumentResponse(val *PrintDocumentResponse) *NullablePrintDocumentResponse {
	return &NullablePrintDocumentResponse{value: val, isSet: true}
}

func (v NullablePrintDocumentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrintDocumentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


