/*
Shipping APIs

The Shipping APIs include a variety of operations that allow users to manage and track their shipping requests.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sp360shipping

import (
	"encoding/json"
)

// checks if the InternationalShipmentResponseCustomsCustomsItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternationalShipmentResponseCustomsCustomsItemsInner{}

// InternationalShipmentResponseCustomsCustomsItemsInner struct for InternationalShipmentResponseCustomsCustomsItemsInner
type InternationalShipmentResponseCustomsCustomsItemsInner struct {
	// A detailed description of the commodity, up to 255 characters. The description will appear on the customs form. If the shipment has multiple types of items, create a separate customsItems object for each. Each description will appear on the form.
	Description *string `json:"description,omitempty"`
	// The destination country’s tariff-classification number (HS code) for the commodity. Most countries use the six-digit Harmonized System (HS) as the basis for their tariff classifications and then add digits for more detail. The maximum length for an HS code is 14 characters. The HS code will appear on the customs form. If the shipment has multiple types of items, create a separate customsItems object for each.
	HSTariffCode *string `json:"hSTariffCode,omitempty"`
	// The two-character ISO country code of the shipment’s origin country. Use ISO 3166-1 Alpha-2 standard values.
	OriginCountryCode *string `json:"originCountryCode,omitempty"`
	// Enter the total number of items of this type of commodity.
	Quantity *float32 `json:"quantity,omitempty"`
	// The price of one item of this type of commodity.
	UnitPrice *float32 `json:"unitPrice,omitempty"`
	// WeightUnit is a standard for measuring the physical quantities of specified weight. <br> The valid values are:  <br>- OZ: Ounces <br>- GM: Grams <br>- LB: Pounds <br>- KG: Kilograms For USPS shipments, set this to OZ.
	WeightUnit *string `json:"weightUnit,omitempty"`
	// Weight is the measure of how heavy an object is.
	Weight *float32 `json:"weight,omitempty"`
}

// NewInternationalShipmentResponseCustomsCustomsItemsInner instantiates a new InternationalShipmentResponseCustomsCustomsItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternationalShipmentResponseCustomsCustomsItemsInner() *InternationalShipmentResponseCustomsCustomsItemsInner {
	this := InternationalShipmentResponseCustomsCustomsItemsInner{}
	return &this
}

// NewInternationalShipmentResponseCustomsCustomsItemsInnerWithDefaults instantiates a new InternationalShipmentResponseCustomsCustomsItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternationalShipmentResponseCustomsCustomsItemsInnerWithDefaults() *InternationalShipmentResponseCustomsCustomsItemsInner {
	this := InternationalShipmentResponseCustomsCustomsItemsInner{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) SetDescription(v string) {
	o.Description = &v
}

// GetHSTariffCode returns the HSTariffCode field value if set, zero value otherwise.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetHSTariffCode() string {
	if o == nil || IsNil(o.HSTariffCode) {
		var ret string
		return ret
	}
	return *o.HSTariffCode
}

// GetHSTariffCodeOk returns a tuple with the HSTariffCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetHSTariffCodeOk() (*string, bool) {
	if o == nil || IsNil(o.HSTariffCode) {
		return nil, false
	}
	return o.HSTariffCode, true
}

// HasHSTariffCode returns a boolean if a field has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) HasHSTariffCode() bool {
	if o != nil && !IsNil(o.HSTariffCode) {
		return true
	}

	return false
}

// SetHSTariffCode gets a reference to the given string and assigns it to the HSTariffCode field.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) SetHSTariffCode(v string) {
	o.HSTariffCode = &v
}

// GetOriginCountryCode returns the OriginCountryCode field value if set, zero value otherwise.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetOriginCountryCode() string {
	if o == nil || IsNil(o.OriginCountryCode) {
		var ret string
		return ret
	}
	return *o.OriginCountryCode
}

// GetOriginCountryCodeOk returns a tuple with the OriginCountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetOriginCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.OriginCountryCode) {
		return nil, false
	}
	return o.OriginCountryCode, true
}

// HasOriginCountryCode returns a boolean if a field has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) HasOriginCountryCode() bool {
	if o != nil && !IsNil(o.OriginCountryCode) {
		return true
	}

	return false
}

// SetOriginCountryCode gets a reference to the given string and assigns it to the OriginCountryCode field.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) SetOriginCountryCode(v string) {
	o.OriginCountryCode = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetQuantity() float32 {
	if o == nil || IsNil(o.Quantity) {
		var ret float32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float32 and assigns it to the Quantity field.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) SetQuantity(v float32) {
	o.Quantity = &v
}

// GetUnitPrice returns the UnitPrice field value if set, zero value otherwise.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetUnitPrice() float32 {
	if o == nil || IsNil(o.UnitPrice) {
		var ret float32
		return ret
	}
	return *o.UnitPrice
}

// GetUnitPriceOk returns a tuple with the UnitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetUnitPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.UnitPrice) {
		return nil, false
	}
	return o.UnitPrice, true
}

// HasUnitPrice returns a boolean if a field has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) HasUnitPrice() bool {
	if o != nil && !IsNil(o.UnitPrice) {
		return true
	}

	return false
}

// SetUnitPrice gets a reference to the given float32 and assigns it to the UnitPrice field.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) SetUnitPrice(v float32) {
	o.UnitPrice = &v
}

// GetWeightUnit returns the WeightUnit field value if set, zero value otherwise.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetWeightUnit() string {
	if o == nil || IsNil(o.WeightUnit) {
		var ret string
		return ret
	}
	return *o.WeightUnit
}

// GetWeightUnitOk returns a tuple with the WeightUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetWeightUnitOk() (*string, bool) {
	if o == nil || IsNil(o.WeightUnit) {
		return nil, false
	}
	return o.WeightUnit, true
}

// HasWeightUnit returns a boolean if a field has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) HasWeightUnit() bool {
	if o != nil && !IsNil(o.WeightUnit) {
		return true
	}

	return false
}

// SetWeightUnit gets a reference to the given string and assigns it to the WeightUnit field.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) SetWeightUnit(v string) {
	o.WeightUnit = &v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetWeight() float32 {
	if o == nil || IsNil(o.Weight) {
		var ret float32
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) GetWeightOk() (*float32, bool) {
	if o == nil || IsNil(o.Weight) {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) HasWeight() bool {
	if o != nil && !IsNil(o.Weight) {
		return true
	}

	return false
}

// SetWeight gets a reference to the given float32 and assigns it to the Weight field.
func (o *InternationalShipmentResponseCustomsCustomsItemsInner) SetWeight(v float32) {
	o.Weight = &v
}

func (o InternationalShipmentResponseCustomsCustomsItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternationalShipmentResponseCustomsCustomsItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.HSTariffCode) {
		toSerialize["hSTariffCode"] = o.HSTariffCode
	}
	if !IsNil(o.OriginCountryCode) {
		toSerialize["originCountryCode"] = o.OriginCountryCode
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.UnitPrice) {
		toSerialize["unitPrice"] = o.UnitPrice
	}
	if !IsNil(o.WeightUnit) {
		toSerialize["weightUnit"] = o.WeightUnit
	}
	if !IsNil(o.Weight) {
		toSerialize["weight"] = o.Weight
	}
	return toSerialize, nil
}

type NullableInternationalShipmentResponseCustomsCustomsItemsInner struct {
	value *InternationalShipmentResponseCustomsCustomsItemsInner
	isSet bool
}

func (v NullableInternationalShipmentResponseCustomsCustomsItemsInner) Get() *InternationalShipmentResponseCustomsCustomsItemsInner {
	return v.value
}

func (v *NullableInternationalShipmentResponseCustomsCustomsItemsInner) Set(val *InternationalShipmentResponseCustomsCustomsItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableInternationalShipmentResponseCustomsCustomsItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableInternationalShipmentResponseCustomsCustomsItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternationalShipmentResponseCustomsCustomsItemsInner(val *InternationalShipmentResponseCustomsCustomsItemsInner) *NullableInternationalShipmentResponseCustomsCustomsItemsInner {
	return &NullableInternationalShipmentResponseCustomsCustomsItemsInner{value: val, isSet: true}
}

func (v NullableInternationalShipmentResponseCustomsCustomsItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternationalShipmentResponseCustomsCustomsItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


