/*
Shipping APIs

The Shipping APIs include a variety of operations that allow users to manage and track their shipping requests.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sp360shipping

import (
	"encoding/json"
)

// checks if the GetCarrierAccount200ResponseCarrierAccountsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCarrierAccount200ResponseCarrierAccountsInner{}

// GetCarrierAccount200ResponseCarrierAccountsInner struct for GetCarrierAccount200ResponseCarrierAccountsInner
type GetCarrierAccount200ResponseCarrierAccountsInner struct {
	// A unique identifier assigned to the specific carrier account.
	CarrierAccountId *string `json:"carrierAccountId,omitempty"`
	// Name of the carrier.
	CarrierName *string `json:"carrierName,omitempty"`
}

// NewGetCarrierAccount200ResponseCarrierAccountsInner instantiates a new GetCarrierAccount200ResponseCarrierAccountsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCarrierAccount200ResponseCarrierAccountsInner() *GetCarrierAccount200ResponseCarrierAccountsInner {
	this := GetCarrierAccount200ResponseCarrierAccountsInner{}
	return &this
}

// NewGetCarrierAccount200ResponseCarrierAccountsInnerWithDefaults instantiates a new GetCarrierAccount200ResponseCarrierAccountsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCarrierAccount200ResponseCarrierAccountsInnerWithDefaults() *GetCarrierAccount200ResponseCarrierAccountsInner {
	this := GetCarrierAccount200ResponseCarrierAccountsInner{}
	return &this
}

// GetCarrierAccountId returns the CarrierAccountId field value if set, zero value otherwise.
func (o *GetCarrierAccount200ResponseCarrierAccountsInner) GetCarrierAccountId() string {
	if o == nil || IsNil(o.CarrierAccountId) {
		var ret string
		return ret
	}
	return *o.CarrierAccountId
}

// GetCarrierAccountIdOk returns a tuple with the CarrierAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCarrierAccount200ResponseCarrierAccountsInner) GetCarrierAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierAccountId) {
		return nil, false
	}
	return o.CarrierAccountId, true
}

// HasCarrierAccountId returns a boolean if a field has been set.
func (o *GetCarrierAccount200ResponseCarrierAccountsInner) HasCarrierAccountId() bool {
	if o != nil && !IsNil(o.CarrierAccountId) {
		return true
	}

	return false
}

// SetCarrierAccountId gets a reference to the given string and assigns it to the CarrierAccountId field.
func (o *GetCarrierAccount200ResponseCarrierAccountsInner) SetCarrierAccountId(v string) {
	o.CarrierAccountId = &v
}

// GetCarrierName returns the CarrierName field value if set, zero value otherwise.
func (o *GetCarrierAccount200ResponseCarrierAccountsInner) GetCarrierName() string {
	if o == nil || IsNil(o.CarrierName) {
		var ret string
		return ret
	}
	return *o.CarrierName
}

// GetCarrierNameOk returns a tuple with the CarrierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCarrierAccount200ResponseCarrierAccountsInner) GetCarrierNameOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierName) {
		return nil, false
	}
	return o.CarrierName, true
}

// HasCarrierName returns a boolean if a field has been set.
func (o *GetCarrierAccount200ResponseCarrierAccountsInner) HasCarrierName() bool {
	if o != nil && !IsNil(o.CarrierName) {
		return true
	}

	return false
}

// SetCarrierName gets a reference to the given string and assigns it to the CarrierName field.
func (o *GetCarrierAccount200ResponseCarrierAccountsInner) SetCarrierName(v string) {
	o.CarrierName = &v
}

func (o GetCarrierAccount200ResponseCarrierAccountsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCarrierAccount200ResponseCarrierAccountsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CarrierAccountId) {
		toSerialize["carrierAccountId"] = o.CarrierAccountId
	}
	if !IsNil(o.CarrierName) {
		toSerialize["carrierName"] = o.CarrierName
	}
	return toSerialize, nil
}

type NullableGetCarrierAccount200ResponseCarrierAccountsInner struct {
	value *GetCarrierAccount200ResponseCarrierAccountsInner
	isSet bool
}

func (v NullableGetCarrierAccount200ResponseCarrierAccountsInner) Get() *GetCarrierAccount200ResponseCarrierAccountsInner {
	return v.value
}

func (v *NullableGetCarrierAccount200ResponseCarrierAccountsInner) Set(val *GetCarrierAccount200ResponseCarrierAccountsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCarrierAccount200ResponseCarrierAccountsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCarrierAccount200ResponseCarrierAccountsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCarrierAccount200ResponseCarrierAccountsInner(val *GetCarrierAccount200ResponseCarrierAccountsInner) *NullableGetCarrierAccount200ResponseCarrierAccountsInner {
	return &NullableGetCarrierAccount200ResponseCarrierAccountsInner{value: val, isSet: true}
}

func (v NullableGetCarrierAccount200ResponseCarrierAccountsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCarrierAccount200ResponseCarrierAccountsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


